image:
  pullPolicy: Always
  repository: prom/prometheus
  tag: v2.52.0

ports:
  internal: 9090
  external:

serviceName:

resources:
  requests:
    cpu: 100m
    memory: 512Mi
  limits:
    cpu: 300m
    memory: 1024Mi
